retis: workaround build failure for c8s
With rust-toolset 1.75.0 a new failure appeared:

+ /usr/bin/env CARGO_HOME=.cargo 'RUSTFLAGS=-Copt-level=3 -Cdebuginfo=2 -Ccodegen-units=1 %{expr:0 && ("x86_64" != "ppc64le" && "x86_64" != "s390x" && "x86_64" != "i386") ? "-Cforce-frame-pointers=yes" : ""} %[0 ? "-Clink-arg=%_package_note_flags" : ""]' /usr/bin/cargo build -j4 --release
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/builddir/.cargo/bin/rustc - --crate-name ___ --print=file-names -Copt-level=3 -Cdebuginfo=2 -Ccodegen-units=1 '%{expr:0' '&&' '("x86_64"' ''\!'=' '"ppc64le"' '&&' '"x86_64"' ''\!'=' '"s390x"' '&&' '"x86_64"' ''\!'=' '"i386")' '?' '"-Cforce-frame-pointers=yes"' ':' '""}' '%[0' '?' '"-Clink-arg=%_package_note_flags"' ':' '""]' --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (exit status: 1)
  --- stderr
  error: multiple input filenames provided (first two filenames are `-` and `%{expr:0`)

Temporarily fix this by redefining cargo marcos not to set RUSTFLAGS.

Signed-off-by: Antoine Tenart <atenart@redhat.com>